import Head from 'next/head';
import { useEffect } from 'react'
import io from 'socket.io-client'


// components
import { HomePage } from '@components';

const Home = () => {
  
  // useEffect(() => { socketInitializer() } , [])
  // const socketInitializer = async () => {
  //   await fetch('/api/socket/socket')
  //  let socket = io()

  //   socket.on('connect', () => {
  //     console.log('connected')
      

      
  //   })
  // }

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage />
   
      

    </div>
  );
};

export default Home;
